# Generated by Django 3.2.25 on 2025-06-14 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_hora_creacion_publicacion_fecha_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Astro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('diametro', models.FloatField()),
                ('masa', models.FloatField()),
                ('distancia_sol', models.FloatField()),
                ('periodo_dias', models.FloatField()),
                ('periodo_años', models.FloatField()),
                ('lunas', models.IntegerField()),
                ('escala', models.FloatField()),
                ('rotacion', models.FloatField()),
                ('imagen', models.ImageField(upload_to='astros/')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
