# Generated by Django 3.2.25 on 2025-06-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_astro_lunas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astro',
            name='masa',
            field=models.CharField(max_length=100),
        ),
    ]
