# Generated by Django 3.2.25 on 2025-06-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_astro_masa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astro',
            name='distancia_sol',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='astro',
            name='lunas',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='astro',
            name='periodo_años',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='astro',
            name='periodo_dias',
            field=models.FloatField(blank=True),
        ),
    ]
